name: polarmae
channels:
  - nvidia/label/cuda-12.4.0
  - pytorch
  - defaults
  - nvidia
  - conda-forge
  - iopath
dependencies:
  - python=3.10
  - cuda
  - cudnn
  - gcc=12
  - gxx
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - torchvision
  - iopath
  - h5py
  - numpy
  - lightning
  - lightning-utilities
  - scikit-learn
  - omegaconf
  - pip
  - torchmetrics
  - pybind11
  - mkl=2022.1.0 # https://github.com/pytorch/pytorch/issues/123097
  # optional
  - ipykernel
  - matplotlib
  - plotly
  - tqdm
  - pip:
      - "jsonargparse[signatures]>=4.27.7"